name: unstructured-grid-viz-cookbook-dev
channels:
  - conda-forge
  - pyviz 
dependencies:
  - jupyter-book
  - jupyterlab
  - jupyter_server
  - pip
  - uxarray
  - cartopy
  - dask
  - datashader
  - geoviews
  - holoviews
  - hvplot
  - matplotlib-base
  - netcdf4
  - numba
  - numpy
  - pandas<2.1.0
  - pathlib
  - pre_commit
  - pyarrow<13.0.0
  - pytest
  - pytest-cov
  - requests
  - scikit-learn
  - scipy
  - shapely
  - spatialpandas
  - xarray
  - pip:
      - sphinx-pythia-theme
      - antimeridian
