name: unstructured-grid-viz-cookbook-dev
channels:
  - conda-forge
dependencies:
  - cartopy
  - dask
  - datashader
  - geoviews
  - holoviews
  - hvplot
  - jupyter-book
  - jupyterlab
  - jupyter_server
  - matplotlib-base
  - netcdf4
  - numba
  - numpy
  - pandas
  - pathlib
  - pip
  - pre_commit
  - pyarrow
  - pytest
  - pytest-cov
  - requests
  - scikit-learn
  - scipy
  - shapely
  - spatialpandas
  - sphinx-pythia-theme
  - uxarray
  - xarray
  - pip:
      - antimeridian
      - git+https://github.com/UXARRAY/uxarray.git@main #until UXarray's March or April release
