name: unstructured-grid-viz-cookbook-dev
channels:
  - conda-forge
  - pyviz 
dependencies:
  - jupyter-book
  - jupyterlab
  - jupyter_server
  - pip
  - uxarray
  - matplotlib
  - spatialpandas
  - shapely
  - cartopy
  - holoviews
  - hvplot
  - geoviews
  - pip:
      - sphinx-pythia-theme
      - antimeridian
