name: unstructured-grid-viz-cookbook-dev
channels:
  - conda-forge
  - pyviz 
dependencies:
  - jupyter-book
  - jupyterlab
  - jupyter_server
  - pip
  # - uxarray uncomment when PR 354 is merged
  - matplotlib
  - spatialpandas
  - shapely
  - cartopy
  - holoviews
  - hvplot
  - geoviews
  - pip:
      - sphinx-pythia-theme
      - git+https://github.com/UXARRAY/uxarray.git@philipc2/wrapped-polygons
      - antimeridian
