name: unstructured-grid-viz-cookbook-dev
channels:
  - conda-forge
dependencies:
  - cartopy
  - dask
  - datashader
  - geoviews
  - holoviews
  - hvplot
  - jupyter-book
  - jupyterlab
  - jupyter_server
  - matplotlib-base
  - netcdf4
  - numba
  - numpy
  - pandas<2.1.0
  - pathlib
  - pip
  - pre_commit
  - pyarrow<13.0.0
  - pytest
  - pytest-cov
  - python>=3.9,<3.12
  - requests
  - scikit-learn
  - scipy
  - shapely
  - spatialpandas   
  - uxarray
  - xarray
  - pip:
      - antimeridian
      - git+https://github.com/ProjectPythia/sphinx-pythia-theme.git@theme-update
