name: unstructured-grid-viz-cookbook-dev
channels:
  - conda-forge
dependencies:
  - jupyter-book
  - jupyterlab
  - jupyter_server
  - pip
  - uxarray
  - matplotlib
  - spatialpandas
  - shapely
  - pip:
      - sphinx-pythia-theme
      - antimeridian
